# Generated by Django 4.0.5 on 2022-06-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_meeting_number_course_course_price'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased_Course',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('purchased_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_purchased_course', to='courses.course')),
                ('purchased_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_purchased_user', to='users.users')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
