# Generated by Django 4.0.5 on 2022-06-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_meeting_number_course_course_price'),
        ('users', '0002_purchased_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_course',
            name='purchased_course',
        ),
        migrations.AddField(
            model_name='purchased_course',
            name='purchased_course',
            field=models.ManyToManyField(related_name='course_purchased_course', to='courses.course'),
        ),
    ]
