# Generated by Django 4.0.5 on 2022-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
