# Generated by Django 4.0.5 on 2022-06-19 13:50

from django.db import migrations, models
import meetings.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(default=uuid.uuid4, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=meetings.models.today_utc)),
                ('end_date', models.DateTimeField(default=meetings.models.today_utc)),
                ('user', models.ManyToManyField(blank=True, related_name='user_meetings', to='users.users')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
