# Generated by Django 4.0.5 on 2022-06-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('meetings', '0002_meetings_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_meetings', to='users.tutor'),
        ),
    ]
