# Generated by Django 4.0.5 on 2022-06-18 15:31

import denemeapp.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('MANAGER', 'Manager'), ('TUTOR', 'Tutor')], default='user', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='denemeapp.users')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(default=uuid.uuid4, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=denemeapp.models.today_utc)),
                ('end_date', models.DateTimeField(default=denemeapp.models.today_utc)),
                ('user', models.ManyToManyField(blank=True, related_name='user_meetings', to='denemeapp.users')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
