# Generated by Django 4.0.5 on 2022-06-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='', max_length=100)),
                ('course_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category_name', to='courses.category')),
                ('course_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_owner_name', to='users.users')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
