# Generated by Django 4.0.5 on 2022-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_meeting_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
