# Generated by Django 4.0.5 on 2022-06-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('transaction_type', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to='users.users')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField(default=0)),
                ('user_balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to='users.users')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
