# Generated by Django 4.0.5 on 2022-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangible', '0005_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
