# Generated by Django 4.0.5 on 2022-06-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denemeapp', '0001_initial'),
        ('tangible', '0010_alter_balance_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user_balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to='denemeapp.users'),
        ),
    ]
